/*
 * This file is automatically generated by UnitTestBot. For further information see https://www.utbot.org
 */

#define main main__
#include "../../../src/main.c"
int main_src_main_c(int argc, char *argv[]) {
return main(argc, argv);
}
